### ISSUE TITLE
Debugging in VS 2017 is showing empty veriables only (Ionic 2)

### ISSUE THREAD

**Issue by Rainson12** [Microsoft/cordova-simulate#229]
When running the "Simulate in Browser" function in Visual Studio 2017 the VS Debugger hits the breakpoints but the content of the variables can not be resovled. VS always shows "ReferenceError"
Stack is below and is always similar:

```
ReferenceError: navCtrl is not defined
    at eval (eval at <anonymous> (http://localhost:4400/build/main.js:63437:5), <anonymous>:1:1)
    at http://localhost:4400/build/main.js:63437:5
    at Object.<anonymous> (http://localhost:4400/build/main.js:63471:2)
    at __webpack_require__ (http://localhost:4400/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:4400/build/main.js:24658:77)
    at __webpack_require__ (http://localhost:4400/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:4400/build/main.js:89286:71)
    at __webpack_require__ (http://localhost:4400/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:4400/build/main.js:77912:73)
    at __webpack_require__ (http://localhost:4400/build/main.js:20:30)
```

**Comment by ruslan-bikkinin** [comment]
Hi @Rainson12 does this problem still actual for you? If so, please, provide us more information about your case otherwise it will be closed.
I tried to reproduce your problem using freshly created cordova project but with no luck.

**Comment by Rainson12** [comment]
I'm not using Cordova anymore
