### ISSUE TITLE
Not working with Cordova Android 7.0.0

### ISSUE THREAD

**Issue by Extracreative** [Microsoft/cordova-simulate#257]
This no longer works with Cordova Android 7.0.0 https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

as they have changed the file structure 

> However this a major breaking change for people creating standalone Cordova Android projects. This also means that the locations of files have changed and have been brought in line to the structure used by Android Studio.

**Comment by jwargo** [comment]
I'm experiencing this as well. I created a new project, then try to simulate it and I get the following:

```
C:\Users\jowargo\dev\cstest>cordova platforms
Installed platforms:
  android 7.0.0
  browser 5.0.3
  windows 5.0.0
Available platforms:
  ios ~4.5.4
  osx ~4.0.1
  www ^3.12.0

C:\Users\jowargo\dev\cstest>simulate android
SIM WARNING: Error starting the simulation
SIM ERROR: Project does not include the specified platform: android
    at C:\Users\jowargo\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\cordova-serve\src\platform.js:45:19
    at _fulfilled (C:\Users\jowargo\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\jowargo\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\Users\jowargo\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:816:13)
    at C:\Users\jowargo\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:877:14
    at runSingle (C:\Users\jowargo\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:137:13)
    at flush (C:\Users\jowargo\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
    at Function.Module.runMain (module.js:705:11)
    at startup (bootstrap_node.js:193:16)
```
An interesting side effect of this is that two browser windows open anyway - which is clearly a bug.

**Comment by arjunmenon** [comment]
I am facing the same problem
```java
>$ cordova platform ls
Installed platforms:
  android 7.1.0
Available platforms: 
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
>$ simulate android
SIM WARNING: Error starting the simulation
SIM ERROR: Project does not include the specified platform: android
    at /usr/lib/node_modules/cordova-simulate/node_modules/cordova-serve/src/platform.js:45:19
    at _fulfilled (/usr/lib/node_modules/cordova-simulate/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova-simulate/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova-simulate/node_modules/q/q.js:816:13)
    at /usr/lib/node_modules/cordova-simulate/node_modules/q/q.js:877:14
    at runSingle (/usr/lib/node_modules/cordova-simulate/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/cordova-simulate/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:613:11)

```

**Comment by zeprone** [comment]
this issue comes from cordova-serve.
I opened a pull request on it to fix this. (https://github.com/apache/cordova-serve/pull/7)
once approved / merge / released, I (or anyone else) will need to move the cordova-serve dependency to the right version.
