### ISSUE TITLE
Error starting the simulation

### ISSUE THREAD

**Issue by arpitmca1992** [Microsoft/cordova-simulate#261]
SIM WARNING: Error starting the simulation
SIM ERROR: Project does not include the specified platform: android
    at C:\Users\Devil\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\cordova-serve\src\platform.js:45:19
    at _fulfilled (C:\Users\Devil\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\Devil\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\Users\Devil\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:816:13)
    at C:\Users\Devil\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:877:14
    at runSingle (C:\Users\Devil\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:137:13)
    at flush (C:\Users\Devil\AppData\Roaming\npm\node_modules\cordova-simulate\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:194:16)

**Comment by ruslan-bikkinin** [comment]
@arpitmca1992 just a friendly ping on this.

**Comment by zeprone** [comment]
it may be related to #257

**Comment by ruslan-bikkinin** [comment]
Closing this as duplicate of #257.
