### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by DaanSchuitmaker** [microsoft/cordova-simulate#422]
## Description
When i try to run Cordova in a browser (simulate) from vs code or cli i get an error.
SIM ERROR: TypeError: Cannot read properties of undefined (reading 'replace')

## Steps to Reproduce
Start a new Cordova project and add android platform
run simulate android

[Please, provide us examples of how are you using `cordova-simulate`: code snippets (if you are using API) or command you are running (if you are using CLI tool).]
`simulate android
SIM ERROR: TypeError: Cannot read properties of undefined (reading 'replace')
    at getUserAgent (C:\Users\d.schuitmaker\AppData\Roaming\npm\node_modules\cordova-simulate\src\server\device.js:74:27)
    at Object.getDeviceInfo (C:\Users\d.schuitmaker\AppData\Roaming\npm\node_modules\cordova-simulate\src\server\device.js:20:20)
    at parseOptions (C:\Users\d.schuitmaker\AppData\Roaming\npm\node_modules\cordova-simulate\src\server\simulator.js:248:32)
    at new Simulator (C:\Users\d.schuitmaker\AppData\Roaming\npm\node_modules\cordova-simulate\src\server\simulator.js:27:20)
    at simulate (C:\Users\d.schuitmaker\AppData\Roaming\npm\node_modules\cordova-simulate\src\simulate.js:16:21)
    at Object.<anonymous> (C:\Users\d.schuitmaker\AppData\Roaming\npm\node_modules\cordova-simulate\bin\simulate:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)`

## Software versions
- `cordova-simulate` version: 8.19.2
- OS platform and version: Windows 11 22H2 22621.1992
- NodeJS version: v18.12.1
- Cordova version: 12.0.0 (cordova-lib@12.0.1)
- Cordova-Android/iOS/Windows version: android 12.0.0
- List of installed plugins: "cordova-android": "^12.0.0"
- Does this reproduce on a debug build or release build? no simulation only

**Comment by EzioLi01** [comment]
Hey @DaanSchuitmaker , thanks for reaching us. Actually the simulate version is wrong, the latest cordova-simulate version should be 1.1.6, and it works well on my side, could you please confirm it?

**Comment by EzioLi01** [comment]
Hey @DaanSchuitmaker , do you have any update to this?

**Comment by DaanSchuitmaker** [comment]
On a new install (new virtual) it work so it seems to be a local issue.
Any ideas how to find the issue?

Tried to reinstall vs code, checked npm, cleared the npm cache, clear vs code extenstions.
Nothing seems to help

**Comment by EzioLi01** [comment]
> 

Maybe it caused by incorrect device id. What API command are you used? Only `simulate` or add some arguments for it?

**Comment by DaanSchuitmaker** [comment]
im trying to run it from vscode with the Cordova Tools extensions

launch config

` {
            "name": "Simulate Android in browser",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "chrome",
            "simulatePort": 8000,
            "livereload": true,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        }`

**Comment by EzioLi01** [comment]
Could you please try to `simulate` by termimal in your project folder to open your app?

**Comment by EzioLi01** [comment]
Hey @DaanSchuitmaker , any updates on this?

**Comment by EzioLi01** [comment]
Thanks @DaanSchuitmaker share the details, will reopen this issue and update device list. For now the latest package V1.1.6, the default android device is Nexus6 with 5.0 default os-version. You can try it or some other devices, the fixing will be release on next prod version 1.2.0. Thank you!
